require File.join(File.dirname(__FILE__), 'kraken_helpers.rb')

install_plugins

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.ssh.insert_key = false
  config.ssh.private_key_path = File.expand_path(ENV['KRAKEN_VAGRANT_PRIVATE_KEY'])
  config.ssh.forward_agent = true
  config.ssh.username = 'core'

  config.vm.box = coreos_boxname
  config.vm.box_version = "= #{coreos_release}"
  config.vm.box_url = "#{coreos_url}/#{coreos_release}/coreos_production_vagrant.json"

  config.trigger.before :up, :vm => 'etcd'  do
    info "getting ansible roles"
    run "ansible-galaxy install defunctzombie.coreos-bootstrap --ignore-errors"
    run "touch #{ENV['VAGRANT_CWD']}/rendered/ansible.inventory"
  end

  # array of non master or etcd nodes for ansible inventory
  node_host_data = ""

  (1..(get_num_nodes.to_i + 2)).each do |i| # number of 'node' nodes + master and etcd nodes

    user_data = build_coreos_userdata(i)

    config.vm.define vm_name = user_data[:name] do |config2|
      config2.vm.hostname = vm_name

      if enable_serial_logging
        logdir = File.join(File.dirname(__FILE__), 'log')
        FileUtils.mkdir_p(logdir)

        serialFile = File.join(logdir, "%s-serial.txt" % vm_name)
        FileUtils.touch(serialFile)

        config2.vm.provider :virtualbox do |vb, override|
          vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
          vb.customize ["modifyvm", :id, "--uartmode1", serialFile]
        end
      end

      config2.vm.provider :virtualbox do |vb, override|
        vb.memory = user_data[:mem]
        vb.cpus = user_data[:cpus]
      end

      ip_address = base_ip_address + "#{i+100}"
      config2.vm.network :private_network, ip: ip_address

      # add non-etcd or master ip to the list
      node_host_data += "#{"node-%03d" % (i - 2)} ansible_ssh_host=#{ip_address}\n" if i > 2

      if File.exist?(user_data[:data])
        config2.vm.provision :file, :source => "#{user_data[:data]}", :destination => "/tmp/vagrantfile-user-data"
        config2.vm.provision :shell, :privileged => true, 
        inline: <<-EOF
          mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/
        EOF
      end

      # run ansible
      master_private_ip = base_ip_address + "#{2+100}"

      if base_ip_address + "#{i+100}" == final_node_ip
        render_vars = {
          :ansible_ssh_private_key_file => File.expand_path(ENV['KRAKEN_VAGRANT_PRIVATE_KEY']),
          :master_ip => master_private_ip,
          :etcd_ip => base_ip_address + "#{1+100}",
          :nodes_inventory_info => node_host_data,
          :node_01_ip => base_ip_address + "#{3+100}",
          :kraken_services_repo => ENV['KRAKEN_SERVICES_REPO'],
          :kraken_services_branch => ENV['KRAKEN_SERVICES_BRANCH'],
          :dns_domain => ENV['KRAKEN_DNS_DOMAIN'],
          :dns_ip => ENV['KRAKEN_DNS_IP'],
          :dockercfg_base64 => ENV['KRAKEN_DOCKERCFG_BASE64'],
          :hyperkube_image => ENV['KRAKEN_HYPERKUBE_IMAGE'],
          :kubernetes_version => ENV['KRAKEN_KUBERNETES_VERSION'],
          :kubernetes_api_version => ENV['KRAKEN_KUBERNETES_API_VERSION'],
          :kubernetes_verbosity => ENV['KRAKEN_KUBERNETES_VERBOSITY'],
          :kraken_services_dirs => ENV['KRAKEN_SERVICES_DIRS'],
          :logentries_token => ENV['KRAKEN_LOGENTRIES_TOKEN'],
          :logentries_url => ENV['KRAKEN_LOGENTRIES_URL'],
          :interface_name => ENV['KRAKEN_INTERFACE_NAME'] 
        }

        render("#{ENV['VAGRANT_CWD']}/templates/ansible.inventory.erb", "#{ENV['VAGRANT_CWD']}/rendered/ansible.inventory", render_vars)
        
        config2.vm.provision 'ansible' do |ansible|
          ansible.limit = 'cluster'
          ansible.inventory_path = "#{ENV['VAGRANT_CWD']}/rendered/ansible.inventory"
          ansible.playbook = "../../ansible/vagrant_provision.yaml"
        end
      end
    end
  end
end
