---
- name: Determine which nodes will use which container runtime
  set_fact:
    custom_nodes: "{{ cluster.nodePools
                   | selectattr('containerConfig.runtime', 'equalto', 'docker')
                   | selectattr('containerConfig.type', 'equalto', 'tgz')
                   | list }}"

- name: Generate nodePool .units.exec-docker.part files
  template: src=docker-exec.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ item.name }}.units.exec-docker.part"
  with_items: "{{ custom_nodes }}"

- name: Generate nodePool .units.exec-containerd.part files
  template: src=containerd-exec.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ item.name }}.units.exec-containerd.part"
  with_items: "{{ custom_nodes }}"

- name: Generate node .units.docker-install.part files
  template: src=docker-install.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ item.name }}.units.docker-install.part"
  with_items: "{{ custom_nodes }}"
