---
kind: Namespace
apiVersion: v1
metadata:
  name: cnct
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  namespace: cnct
  name: cnct
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: cnct
  namespace: cnct
subjects:
  - kind: Group
    name: cnct
    namespace: cnct
roleRef:
  kind: Role
  namespace: cnct
  name: cnct
  apiVersion: rbac.authorization.k8s.io/v1alpha1
