
- set_fact:
    cluster: "{{ cluster_node_tuple.0 }}"
    node: "{{ cluster_node_tuple.1 }}"

- name: Look up and set k8s minor version for this cluster
  set_fact:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"

- name: Execute appropriate kubectl per minor version
  set_fact:
    kubectl: "/opt/cnct/kubernetes/{{ kubernetes_minor_version }}/bin/kubectl"
    kubeconfig: "{{ config_base }}/{{ cluster.name }}/admin.kubeconfig"

- name: Collect node names in nodepool
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig }} get nodes -l k2nodepool={{ node.name }} --output=custom-columns=NAME:.metadata.name --no-headers=true
  register: node_names
  ignore_errors: yes

- name: Set node name fact
  set_fact:
    nodes_in_nodepool: "{{ node_names.stdout_lines }}"

- name: Taint nodes by nodeConfig
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig }} taint nodes {{ item.0 }} {{ item.1.key }}={{ item.1.value }}:{{ item.1.effect }}
  with_nested:
    - "{{ nodes_in_nodepool }}"
    - "{{ node.nodeConfig.taints }}"
  when: node.nodeConfig.taints is defined
  ignore_errors: yes

- name: Taint nodes by nodePool
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig }} taint nodes {{ item.0 }} {{ item.1.key }}={{ item.1.value }}:{{ item.1.effect }}
  with_nested:
    - "{{ nodes_in_nodepool }}"
    - "{{ node.schedulingConfig.taints }}"
  when: node.schedulingConfig.taints is defined
  ignore_errors: yes
