---
- hosts: localhost
  roles:
    - { 
        role: 'kraken.config', config_file: "{{ config_path | default('') }}", 
        tags: [ 'config', 'always', 'config_only' ] 
      }
    - { 
        role: 'roles/kraken.services', when: "kraken_config.clusterServices is defined", 
        tags: [ 'services', 'all', 'services_only' ] 
      }
    - { 
        role: 'roles/kraken.provider/kraken.provider.selector', 
        tags: [ 'provider', 'all', 'provider_only' ] 
      }
    - { 
        role: 'roles/kraken.clean', 
        tags: [ 'dryrun', 'all' ] 
      }