- name: Create a list of file for nodes
  find: >
    paths="{{ config_base | expanduser }}/{{kraken_config.cluster}}" 
    patterns="etcd.{{item.name}}.*.part" 
  register: etcd_list
  with_items: "{{kraken_config.etcd}}"

- name: Generate etcd cloud init
  template: src=etcd.yaml.jinja2
    dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/cloud-config/etcd.{{item.0.name}}.cloud-config.yaml"
  with_together: 
    - "{{kraken_config.etcd}}"
    - "{{etcd_list.results}}"